name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create config file
        run: |
          cd Resume_Chatbot
          mkdir -p js
          echo "const HF_TOKEN = '${{ secrets.HF_TOKEN }}';" > js/config.js

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: Resume_Chatbot
          branch: gh-pages
          clean: true